### ISSUE TITLE
video time back to 00:00 if i click track time

### ISSUE THREAD

**Issue by munimation** [zhw2590582/ArtPlayer#122]
Example i click track time to 8:00 but video back to 00:00
please cek [Demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Flh3.googleusercontent.com%2F6BsystYi_fpNMwQOrKGhtOW0IHTJXL1qsGkJ875ZxXI-pcSeU5w2bIXNDqoiJod7VOmNPs9nFWyzOu2W1JoOsj4FZ19AepCFsW7eXTG3DtvuJGH3Cy5tXh7ygjqh1AOVWk8m-IjT2g%3Ddv%27%2C%0A%7D)%3B)

**Comment by zhw2590582** [comment]
This bug seems to be related to Google’s servers, not artplayer: [demo](https://artplayer.org/?libs=&code=const%20%24el%20%3D%20document.querySelector(%27.artplayer-app%27)%3B%0A%24el.innerHTML%20%3D%20%27%3Cvideo%20height%3D%22300%22%20controls%20src%3D%22https%3A%2F%2Flh3.googleusercontent.com%2F6BsystYi_fpNMwQOrKGhtOW0IHTJXL1qsGkJ875ZxXI-pcSeU5w2bIXNDqoiJod7VOmNPs9nFWyzOu2W1JoOsj4FZ19AepCFsW7eXTG3DtvuJGH3Cy5tXh7ygjqh1AOVWk8m-IjT2g%3Ddv%22%3E%3C%2Fvideo%3E%27)

**Comment by munimation** [comment]
Oke thanks for answer, i think this problem from google server too.
