### ISSUE TITLE
Support for multiple audio tracks

### ISSUE THREAD

**Issue by Daxxxis** [zhw2590582/ArtPlayer#292]
Support for videos with multiple audio tracks with different languages

**Comment by AlkenD** [comment]
> Support for videos with multiple audio tracks with different languages

That won't be possible unless you have one video file and multiple audio files and sync them but that is not a good implementation considering the use case. Since the audio files contained inside video cannot be extracted as browsers cannot run container videos like hevc and audio tracks and subtitles within the file this won't workout unless you do anything on the server side you can use ffmpeg and provide multiple streams of urls and use art.switchQuality function to initiate then.

**Comment by zhw2590582** [comment]
Artplayer is just a UI beautification of the native `<video>` tag, it does not have any decoding function itself, The multi-audio track you mentioned is asking whether the native browser supports it, not whether the Artplayer supports it.

**Comment by Daxxxis** [comment]
How about keeping audio in separate files? Can it be linked somehow to Artplayer?

**Comment by zhw2590582** [comment]
@Daxxxis You mean, the audio track and the picture are separate? Then you want to play them in sync?

**Comment by Daxxxis** [comment]
@zhw2590582 Yes, exactly

**Comment by zhw2590582** [comment]
Artplayer obviously can't do this alone, but you can create a new `<audio src="Your audio url">` and play it in sync with artplayer
