### ISSUE TITLE
Autoplay is not working

### ISSUE THREAD

**Issue by dantart** [zhw2590582/ArtPlayer#297]
If you set autoplay: true and load the URL totally from scratch (not reloading same page), autoplay is not working:

Open a new window directly with this link:
https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20poster%3A%20%27%2Fassets%2Fsample%2Fposter.jpg%27%2C%0A%20%20%20%20autoplay%3A%20true%2C%0A%20%20%20%20whitelist%3A%20%5B%27*%27%5D%2C%0A%20%20%20%20moreVideoAttr%3A%20%7B%0A%20%20%20%20%20%20%20%20crossOrigin%3A%20%27anonymous%27%2C%0A%20%20%20%20%7D%0A%7D)%3B

If you then click in "Run code" it works, because there's a click in the page.

https://developer.chrome.com/blog/autoplay/

Then how does Youtube auto play the videos once you load a video page ?
for example, if you go to https://www.youtube.com/watch?v=Kh-OnqCCDgI the video plays automatically (well, first ads, but they are videos too :-)

**Comment by zhw2590582** [comment]
If you enter the page for the first time, you need to set `muted: true`： [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09muted%3A%20true%2C%0A%20%20%20%20autoplay%3A%20true%2C%0A%7D)%3B)

Why Chrome agrees to YouTube's video autoplay because Youtube is Google's.
Or your website is recognized by Google, such as a famous website with tens of millions of views, you will enter the whitelist of automatic playback

**Comment by dantart** [comment]
Thank you ... I have more information ... it's not "because Youtube is Google's" ...
Here is the answer: chrome://media-engagement

One you have a nice ratio, you are allowed to autoplay videos.
